### ISSUE TITLE
[add] .l-contentに具体的な余白の指定方法を追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/dorcss#18]
`.l-content__item`にも内包するコンポーネントに対する余白の指定をする。

```css
.l-content__item {
  margin-bottom: 1.6rem;
}
```

```css
.l-content__item {
  margin-bottom: 1.6rem;
  & > :last-child {
    margin-bottom: 0;
}
```

`<section>`で使うような`.l-content__section`にも`margin-top`などを指定をする。
