### ISSUE TITLE
[update] 命名規則のルール

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/dorcss#3]
## サフィックス（Suffix）

ブレイクポイントを指定しているクラス名は-smや-mdのようなブレイクポイントのキーワードをクラス名の末尾につけます。 ブレイクポイントはグローバル変数として定義しておき、そのキーをクラス名にも使うようにします。

``` scss
$breakpoint-up: (
  'md': 'screen and (min-width: 768px)',
  'lg': 'screen and (min-width: 1000px)',
) !default;
```

``` scss
@media (min-width: 768px) {
  .u-dn-md { display: none; }
}

@media (min-width: 1000px) {
  .u-dn-lg { display: none; }
}
```
## レイヤーとクラス名

Objectコンポーネントには抽象的なクラス名をつけます。構造のみを持ち、インスタンスのよううに使われることもあるからです。

PartsコンポーネントとContainerコンポーネントは具体的なクラス名をつけます。ユーザーインターフェイスとして具体的な役割を持つべきだからです。

LayoutコンポーネントとScopeコンポーネントは範囲を示すクラス名をつけます。コンポーネントというよりも、ある範囲といった意味合いが強いからです。
