### ISSUE TITLE
[update] .t-content__textの余白指定を修正する

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/dorcss#46]
```css
  & > :last-child {
    margin-bottom: 0;
  }
```

ではなく

```css
  &:last-child {
    margin-bottom: 0;
  }
```

のようにする。
