### ISSUE TITLE
[add] @applyの追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/dorcss#9]
三点リーダでの省略とスクリーンリーダー対応。

```css
:root {
  --truncate: {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }
  --srOnly: {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    border: 0;
    overflow: hidden;
    padding: 0;
    clip: rect(0, 0, 0, 0);
  }
}
```
